---

- include: activate-redis.yml
- include: update-caching-settings.yml
- include: create-cron.yml
- include: create-fileadmin.yml
- include: composer.yml
- include: update-configuration.yml
- include: import-db.yml