---

- name: Change php session type to memchacned
  replace: dest=/etc/php/7.0/fpm/php.ini regexp='session.save_handler = files' replace='session.save_handler = memcached'

- name: Set php path to memcached
  replace: dest=/etc/php/7.0/fpm/php.ini regexp='session.save_path =' replace='session.save_path = "127.0.0.1:11211"'

- name: Restart fpm
  service: name=php7.0-fpm state=restarted

- name: Restart Nginx
  service: name=nginx state=restarted